# Generated by Django 3.0.7 on 2020-06-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_check_manual_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='flip',
            name='next_alert_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Denotes the time next alerts should be sent in case this flip does not come back to success from failure', null=True),
        ),
    ]
